@startuml
' hide the spot
' hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

left to right direction

entity "user" as user {
    *id : number <<generated>>
    --
    ' style_id : number<<FK>>
    name : string
    email : string
    password : string
    gender : string
    birthday : date
    image : string
    created_at : datetime <<generated>>
    last_login_at : datetime
    status : tinyint
    role : tinyint
}
entity "account" as account{
    *id : number <<generated>>
    --
    user_id : number <<FK>>
    name : string
    type : tinyint
    description : string
    image : string
    initial_amount : number
    is_public : boolean
    created_at : datetime <<generated>>
}
entity "user_account_follow" as user_account_follow{
    *id : number <<generated>>
    --
    follower_id : number <<FK>>
    account_id : number <<FK>>
    created_at : datetime <<generated>>

}

entity "record" as record{
    *id : number <<generated>>
    --
    user_id : number <<FK>>
    account_id : number <<FK>>
    category_id : number <<FK>>
    item_title : string
    item_note : string
    item_description : string
    item_price : number
    item_image : string
    created_at : datetime <<generated>>
    updated_at : datetime <<generated>>
}


entity "category" as category {
    *id : number <<generated>>
    --
    name : string
    type : tinyint <<notnull>
}

    user ||--|{ record
    account }|--|| user
    record }|--|| category
    record }|--|| account
    user_account_follow }|--|| user
    user_account_follow }|--|| account

@enduml