@startuml
left to right direction
skinparam rectangle {
    BackgroundColor<<design>> LightPink
    BackgroundColor<<complete>> LightGreen
}
skinparam Linetype ortho
skinparam packageStyle rectangle
package member{
    rectangle "Login" <<complete>> as login
    rectangle "Register" <<complete>> as register
    rectangle "Forget Password" <<design>> as forgetPw
    rectangle "Profile" <<complete>> as userProfile
    rectangle "Edit Profile" <<complete>> as editProfile
}

package account{
    rectangle "View Account List" as viewAccountList
    rectangle "Add Account" as addAccount
    rectangle "Edit Account" as editAccount
    rectangle "Search Account" as searchAccount
    rectangle "View Account Detail" as viewAccountDetail
    rectangle "Monthly Repor" as byMonth
    rectangle "View Account wall" as viewAccountWall
}

package style{
    rectangle "View Style List" as viewStyleList
    rectangle "Add Style" as addStyle
    rectangle "Search Style" as searchStyle
    rectangle "Create Style" as createStyle
}

register --> login
login --> viewAccountList
@enduml