@startuml
left to right direction
skinparam rectangle {
    BackgroundColor<<design>> LightPink
    BackgroundColor<<complete>> LightGreen
}
skinparam Linetype ortho
skinparam packageStyle rectangle
package Member{
    rectangle "Login" <<complete>> as login
    rectangle "Register" <<complete>> as register
    rectangle "Forget Password" <<complete>> as forgetPw
    rectangle "Profile" <<complete>> as userProfile
    rectangle "Edit Profile" <<complete>> as editProfile
}

package Account{
    rectangle "View Account List" <<complete>> as viewAccountList
    rectangle "Add Account" <<complete>> as addAccount
    rectangle "Edit Account" <<complete>> as editAccount
    rectangle "Delete Account" <<complete>> as deleteAccount
    rectangle "View Account Detail" <<complete>> as viewAccountDetail
}

package Record{
    rectangle "Overview" <<complete>> as overview
    rectangle "Add Record" <<complete>> as addRecord
    rectangle "Edit Record" <<complete>> as editRecord
    rectangle "Delete Record" <<complete>> as deleteRecord
}

register --> login
login --> viewAccountList
login --> userProfile
login --> overview
userProfile --> editProfile
viewAccountList --> addAccount
viewAccountList --> editAccount
viewAccountList --> deleteAccount
viewAccountList --> viewAccountDetail
overview --> addRecord
overview --> editRecord
overview --> deleteRecord


legend
  <b>功能狀態說明</b>
  <color:LightGreen>■</color> 已完成（Complete）
  <color:LightPink>■</color> 設計中（Design）
endlegend

@enduml